import type { Config } from "tailwindcss";

export default {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#872d00",
        "on-secondary-container": "#00714d",
        "error": "#ba1a1a",
        "on-background": "#0b1c30",
        "on-error-container": "#93000a",
        "inverse-on-surface": "#eaf1ff",
        "surface-container-highest": "#d3e4fe",
        "on-primary": "#ffffff",
        "on-tertiary-container": "#ffa583",
        "on-tertiary-fixed": "#380d00",
        "surface-tint": "#3755c3",
        "surface-container": "#e5eeff",
        "on-surface": "#0b1c30",
        "outline": "#757684",
        "on-tertiary": "#ffffff",
        "on-surface-variant": "#444653",
        "primary": "#00288e",
        "secondary-container": "#6cf8bb",
        "surface-dim": "#cbdbf5",
        "tertiary-fixed-dim": "#ffb59a",
        "on-error": "#ffffff",
        "surface-container-high": "#dce9ff",
        "secondary-fixed-dim": "#4edea3",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed": "#6ffbbe",
        "inverse-primary": "#b8c4ff",
        "error-container": "#ffdad6",
        "primary-container": "#1e40af",
        "surface-container-low": "#eff4ff",
        "surface-bright": "#f8f9ff",
        "tertiary-fixed": "#ffdbce",
        "on-secondary": "#ffffff",
        "tertiary": "#611e00",
        "primary-fixed": "#dde1ff",
        "on-secondary-fixed-variant": "#005236",
        "on-primary-container": "#a8b8ff",
        "outline-variant": "#c4c5d5",
        "surface": "#f8f9ff",
        "background": "#f8f9ff",
        "secondary": "#006c49",
        "surface-variant": "#d3e4fe",
        "primary-fixed-dim": "#b8c4ff",
        "on-primary-fixed": "#001453",
        "inverse-surface": "#213145",
        "on-primary-fixed-variant": "#173bab",
        "on-tertiary-fixed-variant": "#802a00",
        "on-secondary-fixed": "#002113"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "xl": "64px",
        "xs": "4px",
        "base": "8px",
        "md": "24px",
        "sm": "12px",
        "gutter": "24px",
        "lg": "40px",
        "container-max": "1440px"
      },
      fontSize: {
        "body-sm": ["14px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "h3": ["24px", { "lineHeight": "1.3", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "label-md": ["14px", { "lineHeight": "1", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "h2": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "h1": ["40px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "label-sm": ["12px", { "lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
} satisfies Config;
